[Eth]
NetworkId = 1337
SyncMode = "full"
RPCGasCap = 100000000

[Eth.Miner]
# Minimum gas price accepted by the network (wei)
GasPrice = 1000000000
GasCeil = 15000000
Recommit = 3000000000
NewPayloadTimeout = 2000000000

[Eth.TxPool]
NoLocals = false
Journal = ""
Rejournal = 3600000000000
# Minimum gas price accepted in the tx pool (wei)
PriceLimit = 1          # Allow zero gas price for private network
PriceBump = 10          # 10% price increase for replacement

# Account limits optimized for SSI workloads
AccountSlots = 16          # Higher limit for issuer accounts (vs default 16)
GlobalSlots = 5120         # Increased global pool (vs default 5120)
AccountQueue = 256         # Larger queue for pending transactions
GlobalQueue = 1024         # Increased pending queue
Lifetime = 10800000000000  # 3 hours (longer retention for large transactions)

# Gas optimization for SSI operations
[Eth.GPO]
# Gas price oracle configuration
Blocks = 100
Percentile = 50
MaxHeaderHistory = 1024
MaxBlockHistory = 1024
MaxPrice = 500000000000
IgnorePrice = 1

[Node]
# Data directory
DataDir = "/opt/geth/data"
# Clique doesn't need Engine API
AuthAddr = ""
AuthPort = 0

# Enable HTTP-RPC
HTTPHost = "0.0.0.0"
HTTPPort = 8545
# Allowed CORS origins
HTTPCors = ["*"]
# Allowed HTTP Host headers
HTTPVirtualHosts = ["*"]
# Enabled HTTP modules
HTTPModules = ["eth", "net", "clique", "miner", "debug", "txpool", "personal"]

# Enable WebSockets
WSHost = "0.0.0.0"
WSPort = 8546
# Enabled WS modules
WSModules = ["eth", "net", "clique", "miner", "debug", "txpool", "personal"]


[Node.P2P]
ListenAddr = ":30303"
# Disable discovery completely for deterministic mesh topology
NoDiscovery = true    # Critical: Disable all peer discovery mechanisms
# Remove BootstrapNodes - rely only on StaticNodes for deterministic connections
# Use StaticNodes for deterministic connections (all validator nodes + rpcnode)
StaticNodes = [
    "enode://8208a3f344695d44e9cf2c023683cbea7b9343e2f70a5e804bd2c93858e945f8f91439eef96a4ab6c47ff06637d6fbe6472f96de1655a1bee57ea896654f3a22@172.16.239.11:30303",
    "enode://b9050e002aa42464e6b07c811a1f9dfec01249af03f67b753e8415420649b184447bb2a784863ccbf327ad9e31aaba803464979dfe6a7facc669151a5fa6ad1b@172.16.239.12:30303",
    "enode://59cf0c623c582fa9b19bdf70fb6bade07f4ae32218dd4d1c7e2c7e65acf87da45cf2ab55d16d27360aafef17622c37c09db60d7680ebcc17b78867f4c05bcaa4@172.16.239.13:30303",
    "enode://2fd5b5b6ad529f55b71602026d1849d0036f06482368b5812fa793014195d3571b0840dbc4175617de2a12db8f1222c012420d471ae5c0d982118625cae58868@172.16.239.14:30303",
    "enode://86fcc16f4730fbfd238dc17ea552854c0943923bb1d5e886e5601b8d884fb0519060e0023f495dd24ffe60a65660fb7fdcdebfceedd2b3673dfa63658825924b@172.16.239.15:30303"
]
# Limit peers to only these 5 nodes for strict deterministic mesh
MaxPeers = 5