[Eth]
NetworkId = 1337
SyncMode = "full"

[Eth.Miner]
# Minimum gas price accepted by the network (wei)
GasPrice = 0

[Eth.TxPool]
NoLocals = false
# Minimum gas price accepted in the tx pool (wei)
PriceLimit = 0

[Node]
# Data directory
DataDir = "/opt/geth/data"

# Enable HTTP-RPC
HTTPHost = "0.0.0.0"
HTTPPort = 8545
# Allowed CORS origins
HTTPCors = ["*"]
# Allowed HTTP Host headers
HTTPVirtualHosts = ["*"]
# Enabled HTTP modules
HTTPModules = ["eth", "net", "web3", "clique", "miner", "debug", "txpool"]

# Enable WebSockets
WSHost = "0.0.0.0"
WSPort = 8546
# Enabled WS modules
WSModules = ["eth", "net", "web3", "clique", "miner", "debug", "txpool"]

[Node.P2P]
ListenAddr = ":30303"
# Keep discovery enabled
NoDiscovery = false